# Generated by Django 3.0.6 on 2020-09-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200916_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
