# Generated by Django 3.0.6 on 2020-09-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200916_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mediatype',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video')], default='', max_length=300),
        ),
    ]
