# Generated by Django 3.0.6 on 2020-09-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_mediatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mediatype',
            field=models.CharField(choices=[('image', 'image'), ('video', 'video')], max_length=300),
        ),
    ]
