# Generated by Django 3.0.6 on 2020-10-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_user'),
        ('posts', '0007_auto_20200927_0228'),
    ]

    operations = [
    ]
