# Generated by Django 3.0.6 on 2020-09-25 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200923_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_photo',
        ),
    ]
