# Generated by Django 3.0.6 on 2020-10-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20201001_0129'),
        ('users', '0020_auto_20200930_0327'),
    ]

    operations = [
    ]
